// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4b2lSU_foALvayNXBVg28qf-SudhjLuM',
    appId: '1:821240069279:web:3ca30107a228fe3495b6aa',
    messagingSenderId: '821240069279',
    projectId: 'antisomnus-dashboard',
    authDomain: 'antisomnus-dashboard.firebaseapp.com',
    storageBucket: 'antisomnus-dashboard.appspot.com',
    measurementId: 'G-RJKDQFXZJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMPVEZbWmNrkJS_2wkpWjcjWPIFZs9zQ',
    appId: '1:821240069279:android:59a4015a003d13ec95b6aa',
    messagingSenderId: '821240069279',
    projectId: 'antisomnus-dashboard',
    storageBucket: 'antisomnus-dashboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFlM5jVl85EgQ3d2r_Y63CUGucVMhEPU',
    appId: '1:821240069279:ios:80f3144adfbecb3c95b6aa',
    messagingSenderId: '821240069279',
    projectId: 'antisomnus-dashboard',
    storageBucket: 'antisomnus-dashboard.appspot.com',
    iosClientId: '821240069279-i3maoilq9gv22pc6qsf5u5unk9gvvlte.apps.googleusercontent.com',
    iosBundleId: 'com.example.adddFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFlM5jVl85EgQ3d2r_Y63CUGucVMhEPU',
    appId: '1:821240069279:ios:80f3144adfbecb3c95b6aa',
    messagingSenderId: '821240069279',
    projectId: 'antisomnus-dashboard',
    storageBucket: 'antisomnus-dashboard.appspot.com',
    iosClientId: '821240069279-i3maoilq9gv22pc6qsf5u5unk9gvvlte.apps.googleusercontent.com',
    iosBundleId: 'com.example.adddFrontend',
  );
}
